In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
matriz1 = torch.rand(2,3)

In [5]:
matriz1

tensor([[0.5511, 0.6539, 0.2946],
        [0.8914, 0.7707, 0.4681]])

In [6]:
matriz2 = torch.rand_like(matriz1.T)

In [7]:
matriz2

tensor([[0.1499, 0.9604],
        [0.6394, 0.8300],
        [0.3694, 0.6938]])

In [8]:
torch.matmul(matriz1, matriz2)

tensor([[0.6095, 1.2763],
        [0.7993, 1.8206]])

In [9]:
%%time
torch.chain_matmul(matriz1, matriz2)

Wall time: 996 µs


c:\Users\hebertiponsone\Documents\GitHub\MachineLearning\pytorch_env\lib\site-packages\torch\functional.py:1580: UserWarning: torch.chain_matmul is deprecated and will be removed in a future PyTorch release. Use torch.linalg.multi_dot instead, which accepts a list of two or more tensors rather than multiple parameters. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\LinearAlgebra.cpp:971.)
  return _VF.chain_matmul(matrices)  # type: ignore[attr-defined]


tensor([[0.6095, 1.2763],
        [0.7993, 1.8206]])

In [10]:
%%time
torch.matmul(matriz1, matriz2)

Wall time: 0 ns


tensor([[0.6095, 1.2763],
        [0.7993, 1.8206]])

In [11]:
%%time
torch.mm(matriz1, matriz2)

Wall time: 0 ns


tensor([[0.6095, 1.2763],
        [0.7993, 1.8206]])

In [12]:
matriz1.min()

tensor(0.2946)

In [13]:
matriz1.max()

tensor(0.8914)

In [14]:
matriz1.max()

tensor(0.8914)

In [15]:
matriz1.mean()

tensor(0.6050)

In [16]:
torch.min(matriz1)

tensor(0.2946)

### Some title
* blabal
* bububu

In [24]:
seed = 42
torch.manual_seed(seed)
random1 = torch.rand(3,3)
random1

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [28]:
seed = 42
torch.manual_seed(seed)
random2 = torch.rand(3,3)
torch.manual_seed(seed)

random3 = torch.rand(3,3)

random2, random3


(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))